/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NetsuiteAutomationRouteImport } from './routes/netsuite-automation'
import { Route as NetsuiteConsultingRouteImport } from './routes/netsuite-consulting'
import { Route as NetsuiteCustomizationRouteImport } from './routes/netsuite-customization'
import { Route as NetsuiteDataMigrationRouteImport } from './routes/netsuite-data-migration'
import { Route as NetsuiteDevelopmentRouteImport } from './routes/netsuite-development'
import { Route as NetsuiteHealthCheckRouteImport } from './routes/netsuite-health-check'
import { Route as NetsuiteImplementationRouteImport } from './routes/netsuite-implementation'
import { Route as NetsuiteIntegrationRouteImport } from './routes/netsuite-integration'
import { Route as NetsuiteOneworldConsultingRouteImport } from './routes/netsuite-oneworld-consulting'
import { Route as NetsuiteSupportRouteImport } from './routes/netsuite-support'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SuitescriptDevelopmentRouteImport } from './routes/suitescript-development'
import { Route as ThoughtsRouteImport } from './routes/thoughts'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies/index'
import { Route as CaseStudiesCustomerStatementAutomationRouteImport } from './routes/case-studies/customer-statement-automation'
import { Route as CaseStudiesFinanceAutomationJeCreationRouteImport } from './routes/case-studies/finance-automation-je-creation'
import { Route as CaseStudiesLandedCostAutomationRouteImport } from './routes/case-studies/landed-cost-automation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NetsuiteAutomationRoute = NetsuiteAutomationRouteImport.update({
  id: '/netsuite-automation',
  path: '/netsuite-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const NetsuiteConsultingRoute = NetsuiteConsultingRouteImport.update({
  id: '/netsuite-consulting',
  path: '/netsuite-consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const NetsuiteCustomizationRoute = NetsuiteCustomizationRouteImport.update({
  id: '/netsuite-customization',
  path: '/netsuite-customization',
  getParentRoute: () => rootRouteImport,
} as any)
const NetsuiteDataMigrationRoute = NetsuiteDataMigrationRouteImport.update({
  id: '/netsuite-data-migration',
  path: '/netsuite-data-migration',
  getParentRoute: () => rootRouteImport,
} as any)
const NetsuiteDevelopmentRoute = NetsuiteDevelopmentRouteImport.update({
  id: '/netsuite-development',
  path: '/netsuite-development',
  getParentRoute: () => rootRouteImport,
} as any)
const NetsuiteHealthCheckRoute = NetsuiteHealthCheckRouteImport.update({
  id: '/netsuite-health-check',
  path: '/netsuite-health-check',
  getParentRoute: () => rootRouteImport,
} as any)
const NetsuiteImplementationRoute = NetsuiteImplementationRouteImport.update({
  id: '/netsuite-implementation',
  path: '/netsuite-implementation',
  getParentRoute: () => rootRouteImport,
} as any)
const NetsuiteIntegrationRoute = NetsuiteIntegrationRouteImport.update({
  id: '/netsuite-integration',
  path: '/netsuite-integration',
  getParentRoute: () => rootRouteImport,
} as any)
const NetsuiteOneworldConsultingRoute =
  NetsuiteOneworldConsultingRouteImport.update({
    id: '/netsuite-oneworld-consulting',
    path: '/netsuite-oneworld-consulting',
    getParentRoute: () => rootRouteImport,
  } as any)
const NetsuiteSupportRoute = NetsuiteSupportRouteImport.update({
  id: '/netsuite-support',
  path: '/netsuite-support',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitescriptDevelopmentRoute = SuitescriptDevelopmentRouteImport.update({
  id: '/suitescript-development',
  path: '/suitescript-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsRoute = ThoughtsRouteImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesCustomerStatementAutomationRoute =
  CaseStudiesCustomerStatementAutomationRouteImport.update({
    id: '/case-studies/customer-statement-automation',
    path: '/case-studies/customer-statement-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaseStudiesFinanceAutomationJeCreationRoute =
  CaseStudiesFinanceAutomationJeCreationRouteImport.update({
    id: '/case-studies/finance-automation-je-creation',
    path: '/case-studies/finance-automation-je-creation',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaseStudiesLandedCostAutomationRoute =
  CaseStudiesLandedCostAutomationRouteImport.update({
    id: '/case-studies/landed-cost-automation',
    path: '/case-studies/landed-cost-automation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/netsuite-automation': typeof NetsuiteAutomationRoute
  '/netsuite-consulting': typeof NetsuiteConsultingRoute
  '/netsuite-customization': typeof NetsuiteCustomizationRoute
  '/netsuite-data-migration': typeof NetsuiteDataMigrationRoute
  '/netsuite-development': typeof NetsuiteDevelopmentRoute
  '/netsuite-health-check': typeof NetsuiteHealthCheckRoute
  '/netsuite-implementation': typeof NetsuiteImplementationRoute
  '/netsuite-integration': typeof NetsuiteIntegrationRoute
  '/netsuite-oneworld-consulting': typeof NetsuiteOneworldConsultingRoute
  '/netsuite-support': typeof NetsuiteSupportRoute
  '/services': typeof ServicesRoute
  '/suitescript-development': typeof SuitescriptDevelopmentRoute
  '/thoughts': typeof ThoughtsRoute
  '/case-studies/customer-statement-automation': typeof CaseStudiesCustomerStatementAutomationRoute
  '/case-studies/finance-automation-je-creation': typeof CaseStudiesFinanceAutomationJeCreationRoute
  '/case-studies/landed-cost-automation': typeof CaseStudiesLandedCostAutomationRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/netsuite-automation': typeof NetsuiteAutomationRoute
  '/netsuite-consulting': typeof NetsuiteConsultingRoute
  '/netsuite-customization': typeof NetsuiteCustomizationRoute
  '/netsuite-data-migration': typeof NetsuiteDataMigrationRoute
  '/netsuite-development': typeof NetsuiteDevelopmentRoute
  '/netsuite-health-check': typeof NetsuiteHealthCheckRoute
  '/netsuite-implementation': typeof NetsuiteImplementationRoute
  '/netsuite-integration': typeof NetsuiteIntegrationRoute
  '/netsuite-oneworld-consulting': typeof NetsuiteOneworldConsultingRoute
  '/netsuite-support': typeof NetsuiteSupportRoute
  '/services': typeof ServicesRoute
  '/suitescript-development': typeof SuitescriptDevelopmentRoute
  '/thoughts': typeof ThoughtsRoute
  '/case-studies/customer-statement-automation': typeof CaseStudiesCustomerStatementAutomationRoute
  '/case-studies/finance-automation-je-creation': typeof CaseStudiesFinanceAutomationJeCreationRoute
  '/case-studies/landed-cost-automation': typeof CaseStudiesLandedCostAutomationRoute
  '/case-studies': typeof CaseStudiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/netsuite-automation': typeof NetsuiteAutomationRoute
  '/netsuite-consulting': typeof NetsuiteConsultingRoute
  '/netsuite-customization': typeof NetsuiteCustomizationRoute
  '/netsuite-data-migration': typeof NetsuiteDataMigrationRoute
  '/netsuite-development': typeof NetsuiteDevelopmentRoute
  '/netsuite-health-check': typeof NetsuiteHealthCheckRoute
  '/netsuite-implementation': typeof NetsuiteImplementationRoute
  '/netsuite-integration': typeof NetsuiteIntegrationRoute
  '/netsuite-oneworld-consulting': typeof NetsuiteOneworldConsultingRoute
  '/netsuite-support': typeof NetsuiteSupportRoute
  '/services': typeof ServicesRoute
  '/suitescript-development': typeof SuitescriptDevelopmentRoute
  '/thoughts': typeof ThoughtsRoute
  '/case-studies/customer-statement-automation': typeof CaseStudiesCustomerStatementAutomationRoute
  '/case-studies/finance-automation-je-creation': typeof CaseStudiesFinanceAutomationJeCreationRoute
  '/case-studies/landed-cost-automation': typeof CaseStudiesLandedCostAutomationRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/netsuite-automation'
    | '/netsuite-consulting'
    | '/netsuite-customization'
    | '/netsuite-data-migration'
    | '/netsuite-development'
    | '/netsuite-health-check'
    | '/netsuite-implementation'
    | '/netsuite-integration'
    | '/netsuite-oneworld-consulting'
    | '/netsuite-support'
    | '/services'
    | '/suitescript-development'
    | '/thoughts'
    | '/case-studies/customer-statement-automation'
    | '/case-studies/finance-automation-je-creation'
    | '/case-studies/landed-cost-automation'
    | '/case-studies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/netsuite-automation'
    | '/netsuite-consulting'
    | '/netsuite-customization'
    | '/netsuite-data-migration'
    | '/netsuite-development'
    | '/netsuite-health-check'
    | '/netsuite-implementation'
    | '/netsuite-integration'
    | '/netsuite-oneworld-consulting'
    | '/netsuite-support'
    | '/services'
    | '/suitescript-development'
    | '/thoughts'
    | '/case-studies/customer-statement-automation'
    | '/case-studies/finance-automation-je-creation'
    | '/case-studies/landed-cost-automation'
    | '/case-studies'
  id:
    | '__root__'
    | '/'
    | '/netsuite-automation'
    | '/netsuite-consulting'
    | '/netsuite-customization'
    | '/netsuite-data-migration'
    | '/netsuite-development'
    | '/netsuite-health-check'
    | '/netsuite-implementation'
    | '/netsuite-integration'
    | '/netsuite-oneworld-consulting'
    | '/netsuite-support'
    | '/services'
    | '/suitescript-development'
    | '/thoughts'
    | '/case-studies/customer-statement-automation'
    | '/case-studies/finance-automation-je-creation'
    | '/case-studies/landed-cost-automation'
    | '/case-studies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NetsuiteAutomationRoute: typeof NetsuiteAutomationRoute
  NetsuiteConsultingRoute: typeof NetsuiteConsultingRoute
  NetsuiteCustomizationRoute: typeof NetsuiteCustomizationRoute
  NetsuiteDataMigrationRoute: typeof NetsuiteDataMigrationRoute
  NetsuiteDevelopmentRoute: typeof NetsuiteDevelopmentRoute
  NetsuiteHealthCheckRoute: typeof NetsuiteHealthCheckRoute
  NetsuiteImplementationRoute: typeof NetsuiteImplementationRoute
  NetsuiteIntegrationRoute: typeof NetsuiteIntegrationRoute
  NetsuiteOneworldConsultingRoute: typeof NetsuiteOneworldConsultingRoute
  NetsuiteSupportRoute: typeof NetsuiteSupportRoute
  ServicesRoute: typeof ServicesRoute
  SuitescriptDevelopmentRoute: typeof SuitescriptDevelopmentRoute
  ThoughtsRoute: typeof ThoughtsRoute
  CaseStudiesCustomerStatementAutomationRoute: typeof CaseStudiesCustomerStatementAutomationRoute
  CaseStudiesFinanceAutomationJeCreationRoute: typeof CaseStudiesFinanceAutomationJeCreationRoute
  CaseStudiesLandedCostAutomationRoute: typeof CaseStudiesLandedCostAutomationRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/netsuite-automation': {
      id: '/netsuite-automation'
      path: '/netsuite-automation'
      fullPath: '/netsuite-automation'
      preLoaderRoute: typeof NetsuiteAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/netsuite-consulting': {
      id: '/netsuite-consulting'
      path: '/netsuite-consulting'
      fullPath: '/netsuite-consulting'
      preLoaderRoute: typeof NetsuiteConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/netsuite-customization': {
      id: '/netsuite-customization'
      path: '/netsuite-customization'
      fullPath: '/netsuite-customization'
      preLoaderRoute: typeof NetsuiteCustomizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/netsuite-data-migration': {
      id: '/netsuite-data-migration'
      path: '/netsuite-data-migration'
      fullPath: '/netsuite-data-migration'
      preLoaderRoute: typeof NetsuiteDataMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/netsuite-development': {
      id: '/netsuite-development'
      path: '/netsuite-development'
      fullPath: '/netsuite-development'
      preLoaderRoute: typeof NetsuiteDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/netsuite-health-check': {
      id: '/netsuite-health-check'
      path: '/netsuite-health-check'
      fullPath: '/netsuite-health-check'
      preLoaderRoute: typeof NetsuiteHealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/netsuite-implementation': {
      id: '/netsuite-implementation'
      path: '/netsuite-implementation'
      fullPath: '/netsuite-implementation'
      preLoaderRoute: typeof NetsuiteImplementationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/netsuite-integration': {
      id: '/netsuite-integration'
      path: '/netsuite-integration'
      fullPath: '/netsuite-integration'
      preLoaderRoute: typeof NetsuiteIntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/netsuite-oneworld-consulting': {
      id: '/netsuite-oneworld-consulting'
      path: '/netsuite-oneworld-consulting'
      fullPath: '/netsuite-oneworld-consulting'
      preLoaderRoute: typeof NetsuiteOneworldConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/netsuite-support': {
      id: '/netsuite-support'
      path: '/netsuite-support'
      fullPath: '/netsuite-support'
      preLoaderRoute: typeof NetsuiteSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suitescript-development': {
      id: '/suitescript-development'
      path: '/suitescript-development'
      fullPath: '/suitescript-development'
      preLoaderRoute: typeof SuitescriptDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts': {
      id: '/thoughts'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/customer-statement-automation': {
      id: '/case-studies/customer-statement-automation'
      path: '/case-studies/customer-statement-automation'
      fullPath: '/case-studies/customer-statement-automation'
      preLoaderRoute: typeof CaseStudiesCustomerStatementAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/finance-automation-je-creation': {
      id: '/case-studies/finance-automation-je-creation'
      path: '/case-studies/finance-automation-je-creation'
      fullPath: '/case-studies/finance-automation-je-creation'
      preLoaderRoute: typeof CaseStudiesFinanceAutomationJeCreationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/landed-cost-automation': {
      id: '/case-studies/landed-cost-automation'
      path: '/case-studies/landed-cost-automation'
      fullPath: '/case-studies/landed-cost-automation'
      preLoaderRoute: typeof CaseStudiesLandedCostAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NetsuiteAutomationRoute: NetsuiteAutomationRoute,
  NetsuiteConsultingRoute: NetsuiteConsultingRoute,
  NetsuiteCustomizationRoute: NetsuiteCustomizationRoute,
  NetsuiteDataMigrationRoute: NetsuiteDataMigrationRoute,
  NetsuiteDevelopmentRoute: NetsuiteDevelopmentRoute,
  NetsuiteHealthCheckRoute: NetsuiteHealthCheckRoute,
  NetsuiteImplementationRoute: NetsuiteImplementationRoute,
  NetsuiteIntegrationRoute: NetsuiteIntegrationRoute,
  NetsuiteOneworldConsultingRoute: NetsuiteOneworldConsultingRoute,
  NetsuiteSupportRoute: NetsuiteSupportRoute,
  ServicesRoute: ServicesRoute,
  SuitescriptDevelopmentRoute: SuitescriptDevelopmentRoute,
  ThoughtsRoute: ThoughtsRoute,
  CaseStudiesCustomerStatementAutomationRoute:
    CaseStudiesCustomerStatementAutomationRoute,
  CaseStudiesFinanceAutomationJeCreationRoute:
    CaseStudiesFinanceAutomationJeCreationRoute,
  CaseStudiesLandedCostAutomationRoute: CaseStudiesLandedCostAutomationRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
